/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AppHomeHeader: typeof import('./src/components/app/AppHomeHeader.vue')['default']
    AppSidebar: typeof import('./src/components/app/AppSidebar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    DefaultHeader: typeof import('./src/components/default/DefaultHeader.vue')['default']
    DefaultSidebar: typeof import('./src/components/default/DefaultSidebar.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    GoogleAuth: typeof import('./src/components/auth/GoogleAuth.vue')['default']
    GoogleSignIn: typeof import('./src/components/auth/GoogleSignIn.vue')['default']
    HeroItem: typeof import('./src/components/default/home/HeroItem.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LibSearchbar: typeof import('./src/components/default/LibSearchbar.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    MusicLibSearchbar: typeof import('./src/components/default/MusicLibSearchbar.vue')['default']
    MyIcon: typeof import('./src/components/custom/MyIcon.vue')['default']
    MyMenu: typeof import('./src/components/custom/MyMenu.vue')['default']
    MyPinchZoom: typeof import('./src/components/custom/MyPinchZoom.vue')['default']
    MySection: typeof import('./src/components/custom/MySection.vue')['default']
    Password: typeof import('primevue/password')['default']
    PinchZoom: typeof import('./src/components/custom/PinchZoom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreCreator: typeof import('./src/components/app/ScoreCreator.vue')['default']
    ScoreHeader: typeof import('./src/components/app/ScoreHeader.vue')['default']
    ScoreLeftSidebar: typeof import('./src/components/app/ScoreLeftSidebar.vue')['default']
    ScoreList: typeof import('./src/components/app/ScoreList.vue')['default']
    ScoreRightSidebar: typeof import('./src/components/app/ScoreRightSidebar.vue')['default']
    SignInForm: typeof import('./src/components/auth/SignInForm.vue')['default']
    SignUpForm: typeof import('./src/components/auth/SignUpForm.vue')['default']
    Step: typeof import('primevue/step')['default']
    StepList: typeof import('primevue/steplist')['default']
    StepPanel: typeof import('primevue/steppanel')['default']
    StepPanels: typeof import('primevue/steppanels')['default']
    Stepper: typeof import('primevue/stepper')['default']
    SwitchCase: typeof import('./src/components/custom/switch-case/SwitchCase.vue')['default']
    SwitchCaseItem: typeof import('./src/components/custom/switch-case/SwitchCaseItem.vue')['default']
    TieredMenu: typeof import('primevue/tieredmenu')['default']
  }
}
