/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AppHomeHeader: typeof import('./src/components/app/AppHomeHeader.vue')['default']
    AppSidebar: typeof import('./src/components/app/AppSidebar.vue')['default']
    Button: typeof import('primevue/button')['default']
    CenterLine: typeof import('./src/components/app/score/CenterLine.vue')['default']
    ColorPicker: typeof import('primevue/colorpicker')['default']
    DefaultHeader: typeof import('./src/components/default/DefaultHeader.vue')['default']
    DefaultSidebar: typeof import('./src/components/default/DefaultSidebar.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    GoogleAuth: typeof import('./src/components/auth/GoogleAuth.vue')['default']
    HeroItem: typeof import('./src/components/default/home/HeroItem.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MeasurePart: typeof import('./src/components/app/score/parts/MeasurePart.vue')['default']
    MusicLibSearchbar: typeof import('./src/components/default/MusicLibSearchbar.vue')['default']
    MyIcon: typeof import('./src/components/custom/MyIcon.vue')['default']
    MyMenu: typeof import('./src/components/custom/MyMenu.vue')['default']
    MySection: typeof import('./src/components/custom/MySection.vue')['default']
    Note: typeof import('./src/components/app/score/note/Note.vue')['default']
    PinchZoom: typeof import('./src/components/custom/PinchZoom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreCreator: typeof import('./src/components/app/ScoreCreator.vue')['default']
    ScoreCreditText: typeof import('./src/components/app/score/texts/ScoreCreditText.vue')['default']
    ScoreHeader: typeof import('./src/components/app/ScoreHeader.vue')['default']
    ScoreItem: typeof import('./src/components/app/score/ScoreItem.vue')['default']
    ScoreLeftSidebar: typeof import('./src/components/app/ScoreLeftSidebar.vue')['default']
    ScoreList: typeof import('./src/components/app/ScoreList.vue')['default']
    ScoreMeasure: typeof import('./src/components/app/score/ScoreMeasure.vue')['default']
    ScorePage: typeof import('./src/components/app/score/ScorePage.vue')['default']
    ScorePageContent: typeof import('./src/components/app/score/ScorePageContent.vue')['default']
    ScorePart: typeof import('./src/components/app/score/ScorePart.vue')['default']
    ScoreRightSidebar: typeof import('./src/components/app/ScoreRightSidebar.vue')['default']
    ScoreTitle: typeof import('./src/components/app/score/texts/ScoreTitle.vue')['default']
    Select: typeof import('primevue/select')['default']
    SignInForm: typeof import('./src/components/auth/SignInForm.vue')['default']
    SignUpForm: typeof import('./src/components/auth/SignUpForm.vue')['default']
    SolfaNote: typeof import('./src/components/app/score/notes/SolfaNote.vue')['default']
    SwitchCase: typeof import('./src/components/custom/switch-case/SwitchCase.vue')['default']
    SwitchCaseItem: typeof import('./src/components/custom/switch-case/SwitchCaseItem.vue')['default']
    TextEditor: typeof import('./src/components/app/text-editor/TextEditor.vue')['default']
  }
}
