/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHomeHeader: typeof import('./src/components/app/AppHomeHeader.vue')['default']
    AppSidebar: typeof import('./src/components/app/AppSidebar.vue')['default']
    Button: typeof import('primevue/button')['default']
    DefaultHeader: typeof import('./src/components/default/DefaultHeader.vue')['default']
    DefaultSidebar: typeof import('./src/components/default/DefaultSidebar.vue')['default']
    Drawer: typeof import('primevue/drawer')['default']
    GoogleAuth: typeof import('./src/components/auth/GoogleAuth.vue')['default']
    HeroItem: typeof import('./src/components/default/home/HeroItem.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MusicLibSearchbar: typeof import('./src/components/default/MusicLibSearchbar.vue')['default']
    MyIcon: typeof import('./src/components/custom/MyIcon.vue')['default']
    MyMenu: typeof import('./src/components/custom/MyMenu.vue')['default']
    MyPinchZoom: typeof import('./src/components/custom/MyPinchZoom.vue')['default']
    MySection: typeof import('./src/components/custom/MySection.vue')['default']
    PinchZoom: typeof import('./src/components/custom/PinchZoom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreCreator: typeof import('./src/components/app/ScoreCreator.vue')['default']
    ScoreHeader: typeof import('./src/components/app/ScoreHeader.vue')['default']
    ScoreLeftSidebar: typeof import('./src/components/app/ScoreLeftSidebar.vue')['default']
    ScoreList: typeof import('./src/components/app/ScoreList.vue')['default']
    ScoreRightSidebar: typeof import('./src/components/app/ScoreRightSidebar.vue')['default']
    SignInForm: typeof import('./src/components/auth/SignInForm.vue')['default']
    SignUpForm: typeof import('./src/components/auth/SignUpForm.vue')['default']
    SwitchCase: typeof import('./src/components/custom/switch-case/SwitchCase.vue')['default']
    SwitchCaseItem: typeof import('./src/components/custom/switch-case/SwitchCaseItem.vue')['default']
  }
}
